// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');
require('./vendor/ember-data');
require('./templates');


var App = window.App = require('./app');

App.Store = require('./store');

App.BeverageController = require('./controllers/beverage_controller');
App.BeverageTypeController = require('./controllers/beverage_type_controller');
App.EditTapController = require('./controllers/edit_tap_controller');
App.NewBeverageController = require('./controllers/new_beverage_controller');
App.NewBeverageTypeController = require('./controllers/new_beverage_type_controller');
App.NewProducerController = require('./controllers/new_producer_controller');
App.NewStyleController = require('./controllers/new_style_controller');
App.NewTapController = require('./controllers/new_tap_controller');
App.ProducerController = require('./controllers/producer_controller');
App.StyleController = require('./controllers/style_controller');
App.TapController = require('./controllers/tap_controller');
App.Beverage = require('./models/beverage');
App.BeverageType = require('./models/beverage_type');
App.Producer = require('./models/producer');
App.Style = require('./models/style');
App.Tap = require('./models/tap');
App.BeverageTypesRoute = require('./routes/beverage_types_route');
App.BeveragesRoute = require('./routes/beverages_route');
App.NewBeverageRoute = require('./routes/new_beverage_route');
App.NewBeverageTypeRoute = require('./routes/new_beverage_type_route');
App.NewProducerRoute = require('./routes/new_producer_route');
App.NewStyleRoute = require('./routes/new_style_route');
App.NewTapRoute = require('./routes/new_tap_route');
App.ProducersRoute = require('./routes/producers_route');
App.StylesRoute = require('./routes/styles_route');
App.TapsRoute = require('./routes/taps_route');
App.ImageUploadView = require('./views/image_upload_view');
App.NavView = require('./views/nav_view');

require('./routes');

